name: "Build and Test"

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-11 g++-11 \
            libboost-all-dev \
            libeigen3-dev
      - name: Full Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build/debug
          setup-options: -Db_test=true --buildtype=debug -Db_coverage=false -Db_benchmark=false
          options: --verbose
          meson-version: 0.61.2
          ninja-version: 1.2.1        
      - name: Run Unit Tests
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: test
          directory: build/debug
          setup-options: -Db_test=true --buildtype=debug -Db_coverage=false -Db_benchmark=false
          options: --verbose
          meson-version: 0.61.2
          ninja-version: 1.2.1          
      - name: Preserve Build Log on Failure
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: Linux_Meson_log
          path: build/debug/meson-logs/meson-log.txt
