name: "Build and Test"

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v1
    - name: Install Dependencies
      run: |
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends \
        gcc-11 g++-11 \
        libboost-all-dev \
        libeigen3-dev
    - name: Full Build
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: build
        directory: build/debug
        setup-options: -Db_test=true --buildtype=debug -Db_coverage=false -Db_benchmark=false
        options: --verbose
        meson-version: 0.61.2
    - name: Run Unit Tests
      uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        directory: build/debug
        setup-options: -Db_test=true --buildtype=debug -Db_coverage=false -Db_benchmark=false
        options: --verbose
        meson-version: 0.61.2
