name: ci_meson

on:
  push:
    paths:
      - "**.cc"
      - "**.hpp"
  pull_request:
    paths:
      - "**.cc"
      - "**.hpp"

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: meson test -C builddir/ -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: builddir/meson-logs/testlog.txt
    - run: ninja clang-format-check -C builddir/
    - run: ninja clangtidy -C builddir/
