name: "Clang-Tidy"

on:
  workflow_run:
    workflows: ["Build and Test"]
    types: [completed]
  push:
    branches: [update_workflows]
  workflow_dispatch:

jobs:
  run-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            gcc-11 g++-11 \
            libboost-all-dev \
            libeigen3-dev \
            nlohmann-json3-dev \
            clang-tidy
          pip install ninja==1.11.1
          pip install meson==1.1.1
      # Avoid using BSFishy/meson-build@v1.0.3's broken tidy action
      - name: Setup Build
        run: |
          meson setup build/debug -Db_test=false --buildtype=debug -Db_coverage=false -Db_benchmark=false
      - name: Run Clang-Tidy
        run: ninja clang-tidy -C build/debug
      - name: Preserve Build Log on Failure
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: Linux_Meson_log
          path: build/debug/meson-logs/meson-log.txt
